### PR TITLE
Load locally cached data before querying GitHub

### LINKED ISSUE #4: Cache projects for at least 24 hours
Repos don't change that often, we should look into caching things for a little while.

### PR DESCRIPTION
**Pull request by mesozoic**
This will let us close #4 without having to check in our GitHub credentials (as in #15). I didn't actually commit the JSON data because I wanted to keep the pull request short, but I've tested the script. (If we merge this, I'll push another commit to master to refresh the data right afteward.) 

We first load JSON from our own site, then we query the GitHub API. If it's not available, the cached data is going to be good enough for the page to render right away.

I also fixed a bug where we weren't loading more than one page of organization members.

FYI @tomelm

### CODE REVIEW

**Comment by tomelm** [comment]
This looks good, thanks for doing this!

**Comment by tomelm** [comment]
@mesozoic is this safe to merge or will projects disappear until the other PR comes in?

**Comment by mesozoic** [comment]
This is safe to merge. It preserves status quo, since our current page has no project data until it can read the GitHub API. I'll open the next PR with data now.

**Comment by tomelm** [comment]
Sounds good! Merging both

**Pull request merged**
